<?php

/**
 * @file drupalcons.module
 * Demo module for Session #FlyViews. Views and Page Manager (CTools) integration with the #FlyViews Source website.
 */

/**
 * Implements hook_menu().
 */
function shanti_kmaps_utils_menu() {
  $items = array();
  /*
  $items['admin/config/services/shanti_kmaps_utils'] = array(
    'title' => 'SHANTI KMaps Utilities settings',
    'description' => t('Settings for SHANTI KMaps API, eg. endpoint URL etc.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('shanti_kmaps_utils_admin_form'),
    'access arguments' => array('administer shanti_kmaps_utils'),
    'file' => 'shanti_kmaps_utils.admin.inc',
  );
  */
  $items['shanti_kmaps_utils/autocomplete-form'] = array(
    'title' => 'KMaps Autocomplete Test Form',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('shanti_kmaps_utils_autocomplete_test_form'),
    'access arguments' => array('administer shanti_kmaps_utils'),
  );
  $items['shanti_kmaps_utils/autocomplete-func'] = array(
    'title' => 'KMaps Autocomplete Test Function',
    'page callback' => 'shanti_kmaps_utils_autocomplete_test_func',
    'access arguments' => array('administer shanti_kmaps_utils'),
    'type' => MENU_CALLBACK,  
  );
  $items['shanti_kmaps_utils/autocomplete/%/%'] = array(
    'title' => 'KMaps Autocomplete Function',
    'page callback' => 'shanti_kmaps_utils_autocomplete_func',
    'page arguments' => array(2,3),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,  
  );
  $items['shanti_kmaps_utils/test/%/%/%/%/%'] = array(
    'title' => 'KMaps Autocomplete Test Function',
    'page callback' => 'shanti_kmaps_utils_test',
    'page arguments' => array(2,3,4,5,6),
    'access arguments' => array('administer shanti_kmaps_utils'),
    'type' => MENU_CALLBACK,  
  );
  $items['shanti_kmaps_utils/graph/%/%/%'] = array(
    'title' => 'KMaps FancyTree Function',
    'page callback' => 'shanti_kmaps_utils_graph_func',
    'page arguments' => array(2,3,4),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,  
  );
  $items['shanti_kmaps_utils/tree/%/%/%'] = array(
    'title' => 'KMaps Tree Function',
    'page callback' => 'shanti_kmaps_utils_tree_func',
    'page arguments' => array(2,3,4),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,  
  );
  $items['shanti_kmaps_utils/list/%/%/%'] = array(
    'title' => 'KMaps Tree Function',
    'page callback' => 'shanti_kmaps_utils_list_func',
    'page arguments' => array(2,3,4),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,  
  );
  $items['shanti_kmaps_utils/list-uncached/%/%/%'] = array(
    'title' => 'KMaps Tree Function',
    'page callback' => 'shanti_kmaps_utils_list_uncached_func',
    'page arguments' => array(2,3,4),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,  
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function shanti_kmaps_utils_permission() {
  return array(
    'administer shanti_kmaps_utils' => array(
      'title' => t('Administer SHANIT KMaps Utilities'),
    ),
  );
}

function shanti_kmaps_utils_autocomplete_test_form() {
  $form = array();
  $form['kmap_term'] = array(
    '#description' => t('Enter a KMap search term'),
    '#type' => 'textfield',
    '#autocomplete_path' => 'shanti_kmaps_utils/autocomplete-func',
    '#maxlength' => 1024,
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Test',
  );
  return $form;
}

function shanti_kmaps_utils_autocomplete_test_func($string) {
  $request = new KMapsAPI('subjects');
  $matches = $request->searchByName($string); // Need to rename this method and add more
  drupal_json_output($matches);
}

function shanti_kmaps_utils_autocomplete_func($domain = 'subjects', $server = 'production', $string) {
  if (($server == 'production' || $server = 'development') && ($domain == 'subjects' || $domain == 'places')) {
    $request = new KMapsAPI($domain, $server);
    $matches = $request->searchByName($string); 
    drupal_json_output($matches);    
  } else {
    // not a valid request
    return FALSE;
  }
}

// The following are similar -- refactor if you have time

function shanti_kmaps_utils_graph_func($domain = 'subjects', $server = 'production', $string) {
	$result = array();
  if (($server == 'production' || $server = 'development') && ($domain == 'subjects' || $domain == 'places')) {
    $request = new KMapsAPI($domain, $server);
    $result = $request->searchByNameGetGraph($string); // <-- DIFF
  }
  drupal_json_output($result);    
}

function shanti_kmaps_utils_tree_func($domain = 'subjects', $server = 'production', $string) {
	$result = array();
  if (($server == 'production' || $server = 'development') && ($domain == 'subjects' || $domain == 'places')) {
    $request = new KMapsAPI($domain, $server);
    $result = $request->searchByNameGetTree($string); // <-- DIFF
  }
  drupal_json_output($result);
}

function shanti_kmaps_utils_list_func($domain = 'subjects', $server = 'production', $string) {
	$result = array();
  if (($server == 'production' || $server = 'development') && ($domain == 'subjects' || $domain == 'places')) {
    $request = new KMapsAPI($domain, $server);
    $result = $request->searchByNameGetList($string); // <-- DIFF
  }
	drupal_json_output($result);    
}

function shanti_kmaps_utils_list_uncached_func($domain = 'subjects', $server = 'production', $string) {
	$result = array();
  if (($server == 'production' || $server = 'development') && ($domain == 'subjects' || $domain == 'places')) {
    $request = new KMapsAPI($domain, $server);
    $result = $request->searchByNameGetListUncached($string); // <-- DIFF
  }
	drupal_json_output($result);    
}

function shanti_kmaps_utils_test($search, $server = 'production', $domain = 'subjects', $fetch_mode = 'by_fid', $parse_mode = 'autocomplete') {
  if (   
          ($server      == 'production'   || $server      == 'development')
      &&  ($parse_mode  == 'autocomplete' || $parse_mode  == 'raw')
      &&  ($fetch_mode  == 'by_fid'       || $fetch_mode  == 'by_name')
      &&  ($domain      == 'subjects'     || $domain      == 'places')
    ) {
    $request = new KMapsAPI($domain,$server);
    $fetch_mode == 'by_fid' ? $request->setKMapID($search) : $request->setString($search);
    $parse_mode == 'autocomplete' ? $request->setParseModeToAutocomplete() : $request->setParseModeToRaw();
    $request->setFormatToJSON();
    $parsed_data = $request->execute();    
    dpm($parsed_data);
    // Now, collect the KMap IDs and get the info for each item
    drupal_set_message("$search $server $domain $fetch_mode $parse_mode");
    return "SUCCESS " . $request->getURL();    
  } 
  else {
    return "FAIL";
  }
}




