<?php

/**
 * @file shanti_kmaps_utils.index_api.inc
 */

/**
 * Simple class for putting together a URL for the API call, and doing an HTTP request
 * for retrieving information about the KMap Index.
 * All public methods return $this and can be chained together, except the execute(),
 * which returns the response data.  
 */

class KmapsIndexAPI {
  
  // Define private attributes here
    
  public function __construct() {
    return $this;
  }


}